# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'default'
      vmImage: 'azure-agent'

    steps:
    - task: AzureContainerApps@1
      inputs:
        appSourcePath: '$(System.DefaultWorkingDirectory)'
        azureSubscription: 'SuselServiceConnection'
        acrName: 'nginxregistrysusel'
        acrUsername: 'nginxregistrysusel'
        acrPassword: 'xxxxxxxxxxxxxxxxxxxx'
        imageToBuild: 'nginxregistrysusel.azurecr.io/nginxsusel:latest'
        containerAppName: 'susel-container2-app'
        resourceGroup: 'Susel-CI-CD'
        targetPort: '80'
        location: 'eastus'
        ingress: 'external'
